import { getFullDownstreamProjects, getUpstreamProjects } from "@bc-cr/graph";
import { Node } from "@bc-cr/domain/node";
import { getOrderedListForProject, getTreeForProject, parentChainFromNode } from "@bc-cr/tree";
import path from "path";

test.each([
  [
    "kiegroup/lienzo-core",
    ["kiegroup/lienzo-core"]
  ],
  [
    "kiegroup/lienzo-tests",
    ["kiegroup/lienzo-core", "kiegroup/lienzo-tests"]
  ],
  [
    "kiegroup/droolsjbpm-build-bootstrap",
    ["kiegroup/droolsjbpm-build-bootstrap"]
  ],
  [
    "kiegroup/kie-soup",
    ["kiegroup/droolsjbpm-build-bootstrap", "kiegroup/kie-soup"]
  ],
  [
    "kiegroup/appformer",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer"
    ]
  ],
  [
    "kiegroup/droolsjbpm-knowledge",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge"
    ]
  ],
  [
    "kiegroup/drools",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
    ]
  ],
  [
    "kiegroup/jbpm",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
    ]
  ],
  [
    "kiegroup/optaplanner",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner"
    ]
  ],
  [
    "kiegroup/kie-jpmml-integration",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/kie-jpmml-integration"
    ]
  ],
  [
    "kiegroup/droolsjbpm-integration",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration"
    ]
  ],
  [
    "kiegroup/kie-uberfire-extensions",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions"
    ]
  ],
  [
    "kiegroup/kie-wb-playground",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground"
    ]
  ],
  [
    "kiegroup/kie-wb-common",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common"
    ]
  ],
  [
    "kiegroup/drools-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb"
    ]
  ],
  [
    "kiegroup/optaplanner-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb"
    ]
  ],
  [
    "kiegroup/jbpm-work-items",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/optaplanner",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/jbpm-work-items"
    ]
  ],
  [
    "kiegroup/jbpm-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb"
    ]
  ],
  [
    "kiegroup/kie-wb-distributions",
    [
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/process-migration-service",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/process-migration-service"
    ]
  ]
])("getUpstreamProjects for %p", async (project: string, expected: string[]) => {
  const definitionFile = path.join(__dirname, "resources", "graph", "definition-file.yaml");
  const result = await getUpstreamProjects(
    definitionFile, 
    project
  );
  expect(result.map(r => r.project)).toStrictEqual(expected);
  await verifyUpstreamAgainstTreeImplementation(
    definitionFile,
    project,
    result
  );
});

test.each([
  [
    "kiegroup/lienzo-core",
    [
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/lienzo-tests",
    [
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/droolsjbpm-build-bootstrap",
    [
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/kie-soup",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/kie-jpmml-integration",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/kie-soup",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/kie-jpmml-integration",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/appformer",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/droolsjbpm-knowledge",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/kie-jpmml-integration",
      "kiegroup/optaplanner",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/drools",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/kie-jpmml-integration",
      "kiegroup/optaplanner",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/jbpm",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/kie-jpmml-integration",
      "kiegroup/optaplanner",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/optaplanner",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/kie-jpmml-integration",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/kie-jpmml-integration",
    ]
  ],
  [
    "kiegroup/droolsjbpm-integration",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
      "kiegroup/process-migration-service",
    ]
  ],
  [
    "kiegroup/kie-uberfire-extensions",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/kie-wb-playground",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions",
    ]
  ],
  [
    "kiegroup/kie-wb-common",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/drools-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/optaplanner-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/jbpm-work-items",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/jbpm",
      "kiegroup/optaplanner",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/jbpm-work-items",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/jbpm-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/kie-wb-distributions"

    ]
  ],
  [
    "kiegroup/jbpm-wb",
    [
      "kiegroup/lienzo-core",
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/lienzo-tests",
      "kiegroup/kie-soup",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/kie-wb-distributions",
    [
      "kiegroup/droolsjbpm-build-bootstrap",
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/lienzo-core",
      "kiegroup/lienzo-tests",
      "kiegroup/appformer",
      "kiegroup/kie-uberfire-extensions",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/kie-wb-playground",
      "kiegroup/kie-wb-common",
      "kiegroup/drools-wb",
      "kiegroup/jbpm-work-items",
      "kiegroup/jbpm-wb",
      "kiegroup/optaplanner-wb",
      "kiegroup/kie-wb-distributions"
    ]
  ],
  [
    "kiegroup/process-migration-service",
    [
      "kiegroup/droolsjbpm-build-bootstrap", 
      "kiegroup/kie-soup",
      "kiegroup/droolsjbpm-knowledge",
      "kiegroup/drools",
      "kiegroup/optaplanner",
      "kiegroup/jbpm",
      "kiegroup/droolsjbpm-integration",
      "kiegroup/process-migration-service",
    ]
  ]
])("getFullDownstreamProjects for %p", async (project: string, expected: string[]) => {
  const definitionFile = path.join(__dirname, "resources", "graph", "definition-file.yaml");

  const result = await getFullDownstreamProjects(
    definitionFile, 
    project
  );

  expect(result.map(r => r.project)).toStrictEqual(expected);
  await verifyFullDowstreamAgainstTreeImplementation(
    definitionFile,
    project,
    result
  );
});

async function verifyFullDowstreamAgainstTreeImplementation(definitionFile: string, project: string, result: Node[]) {
  const nodes = (await getOrderedListForProject(definitionFile, project)).map(n => n.project);
  const resultNamesOnly = result.map(r => r.project);
  expect(resultNamesOnly.length).toBe(nodes.length);
  for (let i = 0; i < nodes.length; i++) {
    expect(resultNamesOnly.includes(nodes[i])).toBe(true);
  }
}

async function verifyUpstreamAgainstTreeImplementation(definitionFile: string, project: string, result: Node[]) {
  const node = await getTreeForProject(definitionFile, project);
  const nodes = parentChainFromNode(node!).map(n => n.project);
  const resultNamesOnly = result.map(r => r.project);
  expect(resultNamesOnly.length).toBe(nodes.length);
  for (let i = 0; i < nodes.length; i++) {
    expect(resultNamesOnly.includes(nodes[i])).toBe(true);
  }
}