# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Checks

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:report
      - name: get-package-version
        id: package-version
        run: |
          PACKAGE_VERSION=$(npm version | grep @kie/build-chain-configuration-reader | sed -re "s/'.*': '(.*)',?/\1/g" | tr -d '[:space:]')
          echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
      - name: Update github-action-build-chain 
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.UPDATE_BUILD_CHAIN }}
          repository: kiegroup/github-action-build-chain
          event-type: update-build-chain-configuration-reader
          client-payload: '{"version": "${{ steps.package-version.outputs.current-version }}"}'
