on:
  push:
    branches:
      - main
      - typescript/main
    pull_request:
      types: [opened, reopened]

name: coverage report

jobs:
  test-coverage:
    name: Publish coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: coverage report
        uses: actions/setup-node@v1
        with:
          # node 12 support is deprecated in sonar
          node-version: 14
      - run: npm ci
      - run: npm run test:report
      - run: sonar-scanner
          -Dsonar.organization=kiegroup
          -Dsonar.projectKey=kiegroup_build-chain-configuration-reader
          -Dsonar.projectName="Build Chain Configuration Reader"
          -Dsonar.sources=$GITHUB_WORKSPACE
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.tests=test
          -Dsonar.testExecutionReportPaths=test-report.xml
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.exclusions=test/**,**/__mocks__/**,jest.config.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
